version: 0.2

env:
  parameter-store:
    SONATYPE_USERNAME: "sonatype-username"
    SONATYPE_PASSWORD: "sonatype-password"
    SONATYPE_KEY_PASSWORD: "sonatype-key-password"
    SONATYPE_SECRET_KEY: "sonatype-secret-key"

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - chmod +x ./gradlew
  pre_build:
    commands:
      - export PROJECT_VERSION=v`egrep "^version" build.gradle | cut -f2 -d\'`
      - echo Project version is ${PROJECT_VERSION}
  build:
    commands:
      - ./gradlew --console=plain clean build -x dependencyCheckAnalyze
  post_build:
    commands:
      - ./gradlew uploadArchives -PnexusUsername=${SONATYPE_USERNAME} -PnexusPassword=${SONATYPE_PASSWORD} -Psigning.key=${SONATYPE_SECRET_KEY} -Psigning.password=${SONATYPE_KEY_PASSWORD}
