version: 0.2

env:
  parameter-store:
    ORG_GRADLE_PROJECT_nexusUsername: "sonatype-username"
    ORG_GRADLE_PROJECT_nexusPassword: "sonatype-password"
    ORG_GRADLE_PROJECT_signingKey: "sonatype-secret-key"
    ORG_GRADLE_PROJECT_signingPassword: "sonatype-key-password"

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - chmod +x ./gradlew
  pre_build:
    commands:
      - export PROJECT_VERSION=v`egrep "^version" build.gradle | cut -f2 -d\'`
      - echo Project version is ${PROJECT_VERSION}
  build:
    commands:
      - ./gradlew --console=plain clean build -x dependencyCheckAnalyze
  post_build:
    commands:
      - ./gradlew uploadArchives
      - |
        if expr "${CODEBUILD_INITIATOR}" : "codepipeline*" >/dev/null; then
          ./gradlew uploadArchives
        fi
      - |
        if expr "${PROJECT_VERSION}" : "v\([0-9]\{1,\}\.\)\{2\}[0-9]\{1,\}$" >/dev/null; then
          if expr "${CODEBUILD_INITIATOR}" : "codepipeline*" >/dev/null; then
            ./gradlew closeAndReleaseRepository
          fi
        fi
